---
# Configuration for `https://github.com/conan-io/conan-center-index-staging` repository
id: 'conan-io/conan-center-index-staging'

conan:
  version: 1.52.0
  random_field: "this is just to test something"

artifactory:
  url: "https://c3istg.jfrog.io/c3istg"
  main_repo: "danimtb_conan-center"
  pull-request_repo_prefix: "danimtb_PR"
  pull-request_permission: "c3i-pr"
  logs_repo: "danimtb_logs"
  cache_repo: "cache"

github:
  reviewers: "reviewers.yml"
  authorized_users: "authorized_users.yml"

status_checks:
  - "continuous-integration/jenkins/pr-merge"

slack:
  credential_success_url: SLACK_SUCCESS_WEBHOOK_URL
  ceredential_errors_url: SLACK_FAILURE_WEBHOOK_URL

# Connection to conancenter backend
# conancenter:
#   url_log: 'https://conancenter-server---we-need-a-url-here'

# Things related to Jenkins jobs:
tasks:
  conan_v2_run_export: false
  write_comments: true
  detailed_status_checks: true
  update_labels: true
  automatic_merge:
    reviews_required_total: 1  # Reviews that a PR needs so it can be merged
    reviews_required_team: 1  # Reviews from the Conan team that a PR needs so it can be merged

configurations:
  - id: linux-gcc
    epochs: [0]
    hrname: "Linux, GCC"
    content:
      - os: ["Linux"]
        arch: ["x86_64"]
        compiler:
          - "gcc":
              compiler.libcxx: ["libstdc++11", "libstdc++"]
              compiler.version: ["5", "10"]
              build_type: ["Release", "Debug"]

jenkins:
  url: "http://mb-jenkins-my-bloody-jenkins:8080"

node_labels:
  default: "linux_gcc_8.0"
  Windows:
    x86_64:
      "Visual Studio":
        default: "windows"
  Macos:
    x86_64:
      "apple-clang":
        default: "mac_apple_clang_${compiler.version}"
    armv8:
      "apple-clang":
        default: "mac_apple_clang_${compiler.version}"
  Linux:
    x86_64:
      "gcc":
        default: "linux_gcc_${compiler.version}"
        "11": "linux_gcc_${compiler.version}_ubuntu16.04"
      "clang":
        default: "linux_clang_${compiler.version}_ubuntu16.04"
        "11": "linux_clang_${compiler.version}"

pod_size:
  # Map with references that need special memory resources to compile.
  #   - Can be only by name or by name/version.
  #   - name/version notation takes preference over the name only one
  #   - Both notations can be combined for the same reference name
  large:
    - "pcl"
  xlarge:
    - "llvm"
